source 'https://rubygems.org'

# Specify your gem's dependencies in hancock_cms_activerecord.gemspec
gemspec

# gem 'mongo_session_store-rails4', github: 'drgcms/mongo_session_store', branch: 'rails5'
gem 'mongo_session_store-rails5', github: 'ack43/mongo_session_store'#, branch: 'rails5'
